language: php
php:
   - 5.4
   - 5.5
   - 5.6
   - hhvm
before_install:
    sudo apt-get update -q

script:
    php tags.php

notifications:
    email:
        recipients:
            - cvetomirdenchev@gmail.com
        on_success: always
        on_failure: always

branches:
    only: ["master"]
